app/components/admin/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo

class UserForm(FlaskForm):

    name = StringField('Nama Pengguna', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Konfirmasi Password', validators=[DataRequired(), EqualTo('password')])
    is_admin = BooleanField('Centang bila pengguna sebagai administrator.')
    submit = SubmitField('Simpan')

# class PenggunaForm(FlaskForm):
#     name = StringField('Nama Pengguna', validators=[DataRequired()])
#     email = StringField('Email', validators=[DataRequired(), Email()])
#     foto = FileField('Upload Foto', validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'File gambar saja')])
#     submit = SubmitField('Simpan')

class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Password Lama', validators=[DataRequired()])
    password = PasswordField('Password Baru', validators=[DataRequired()])
    confirm_password = PasswordField('Konfirmasi Password Baru', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Ganti Password')

app/components/admin/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/components/admin/users/views.py
from flask import flash, redirect, render_template, url_for, request, session, app
from flask_login import login_required, login_user, logout_user, current_user
from . import users
from ....models import User
from .forms import UserForm, ChangePasswordForm
from .... import db

@users.route('/admin/pengguna', methods=['GET','POST'])
@login_required
def list():
    data = enumerate(User.query.all(), start=1)
    form = UserForm()
    if form.validate_on_submit():
        user = User(name=form.name.data, password=form.password.data, email=form.email.data, is_admin=form.is_admin.data)
        db.session.add(user)
        db.session.commit()
        
        flash('Pengguna baru telah ditambahkan.')
        return redirect(url_for('users.list'))
    
    return render_template('users/users.html', data=data, form=form, title='Pengguna')

@users.route('/admin/pengguna/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    user = User.query.get_or_404(id)
    form = UserForm(obj=user)
    if form.validate_on_submit():
        user.name = form.name.data
        user.password = form.password.data
        user.email = form.email.data
        user.is_admin = form.is_admin.data
        
        db.session.commit()
        flash('Data Pengguna telah diubah.')
        return redirect(url_for('users.list'))
    
    form.name.data = user.name
    form.email.data = user.email
    form.is_admin.data = user.is_admin
    return render_template('users/edit.html', form=form, user=user, title='Edit Pengguna')

@users.route('/admin/pengguna/<id>/hapus', methods=['GET', 'POST'])
@login_required
def delete(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    flash('Pengguna telah dihapus.')
    return redirect(url_for('users.list'))

app/templates/users/edit.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base_admin.html" %}

{% block styles %}
{% endblock styles %}
    
{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/admin"><i class="fas fa-tachometer-alt"></i> Beranda Administrator</a></li>
    <li class="breadcrumb-item"><a href="/admin/pengguna"><i class="fas fa-users"></i> Pengguna</a></li>
    <li class="breadcrumb-item active">{{title}}</li>
</ol>
{% endblock breadcrumbs %}

{% block contents %}
{{ utils.flashed_messages(dismissible=True) }}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
            </div>
            <div class="col-6 text-center">
                <img src="{{ url_for('serveStaticResource', resource='img/faces/face2.jpg')}}" alt="{{ user.name }}-{{ user.email }}" width="300">
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

{% block modals %}
{% endblock modals %}

{% block scripts %}
{% endblock scripts %}

app/templates/users/users.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base_admin.html" %}

{% block styles %}
{% endblock styles %}
    
{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/admin"><i class="fas fa-tachometer-alt"></i> Beranda Administrator</a></li>
    <li class="breadcrumb-item active"><i class="fas fa-file-contract"></i> {{ title }}</li>
</ol>
{% endblock breadcrumbs %}

{% block contents %}
{{ utils.flashed_messages(dismissible=True) }}
<div class="card">
    <div class="card-header text-right">
        <button type="button" class="btn bg-teal waves-effect m-r-20" data-toggle="modal" data-target="#defaultModal">Tambah</button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="myData" class="table table-bordered table-striped table-hover">
                <thead class=>
                    <tr>
                        <th width=5%>No</th>
                        <th>Nama</th>
                        <th>Email</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for no, user in data %}
                    <tr>
                        <td>
                            {{ no }} 
                        </td>
                        <td>
                            {{ user.name }} 
                        </td>
                        <td>
                            {{ user.email }}
                        </td>
                        <td class="text-center">
                            <a class="btn btn-app" href="{{ url_for('users.edit', id=user.id) }}"><i data-toggle="tooltip" data-placement="top" title="Edit" class="fas fa-edit text-info"></i> </a>
                            <a class="btn btn-app" href="{{ url_for('users.delete', id=user.id) }}" onclick="return confirm('Yakin menghapus data ini?');"><i data-toggle="tooltip" data-placement="top" title="Hapus" class="fas fa-trash text-danger"></i> </a>
                        </td>
                    </tr>
                    {% endfor %}       
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock contents %}

{% block modals %}
<div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-right">
                <div class="row">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
             </div>
            <div class="modal-body">
                {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
            </div>
        </div>
    </div>
</div>
{% endblock modals %}

{% block scripts %}
{% endblock scripts %}