app/components/admin/categories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class CategoryForm(FlaskForm):

    name = StringField('Nama', validators=[DataRequired()])
    url_name = StringField('URL')
    desc = TextAreaField('Keterangan')
    submit = SubmitField('Simpan')

app/components/admin/categories/__init__.py
from flask import Blueprint

categories = Blueprint('categories', __name__)

from . import views

app/components/admin/categories/views.py
from flask import flash, redirect, render_template, url_for, request, session, app
from flask_login import login_required, login_user, logout_user, current_user
from . import categories
from ....models import Category
from .forms import CategoryForm
from .... import db

@categories.route('/admin/kategori', methods=['GET','POST'])
@login_required
def list():
    data = enumerate(Category.query.all(), start=1)
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data, url_name=form.url_name.data, desc=form.desc.data)
        db.session.add(category)
        db.session.commit()
        
        flash('Kategori baru telah ditambahkan.')
        return redirect(url_for('categories.list'))
    
    return render_template('categories/categories.html', data=data, form=form, title='Kategori')

@categories.route('/admin/kategori/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    category = Category.query.get_or_404(id)
    form = CategoryForm(obj=category)
    if form.validate_on_submit():
        category.name = form.name.data
        category.desc = form.desc.data
        category.url_name = form.url_name.data
        
        db.session.commit()
        flash('Data kategori telah diubah.')
        return redirect(url_for('categories.list'))
    
    form.name.data = category.name
    form.desc.data = category.desc
    form.url_name.data = category.url_name
    return render_template('categories/edit.html', form=form, category=category, title='Edit Kategori')

@categories.route('/admin/kategori/<id>/hapus', methods=['GET', 'POST'])
@login_required
def delete(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    flash('Kategori telah dihapus.')
    return redirect(url_for('categories.list'))

app/templates/categories/categories.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base_admin.html" %}

{% block styles %}
{% endblock styles %}
    
{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/admin"><i class="fas fa-tachometer-alt"></i> Beranda Administrator</a></li>
    <li class="breadcrumb-item active"><i class="fas fa-file-contract"></i> {{ title }}</li>
</ol>
{% endblock breadcrumbs %}

{% block contents %}
{{ utils.flashed_messages(dismissible=True) }}
<div class="card">
    <div class="card-header text-right">
        <button type="button" class="btn bg-teal waves-effect m-r-20" data-toggle="modal" data-target="#defaultModal">Tambah</button>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="myData" class="table table-bordered table-striped table-hover">
                <thead class=>
                    <tr>
                        <th width=5%>No</th>
                        <th>Nama</th>
                        <th>Keterangan</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for no, category in data %}
                    <tr>
                        <td>
                            {{ no }} 
                        </td>
                        <td>
                            {{ category.name }} <br />
                            <i><small>{{category.url_name}}</small></i>
                        </td>
                        <td>
                            {{ category.desc }}
                        </td>
                        <td class="text-center">
                            <a class="btn btn-app" href="{{ url_for('categories.edit', id=category.id) }}"><i data-toggle="tooltip" data-placement="top" title="Edit" class="fas fa-edit text-info"></i> </a>
                            <a class="btn btn-app" href="{{ url_for('categories.delete', id=category.id) }}" onclick="return confirm('Yakin menghapus data ini?');"><i data-toggle="tooltip" data-placement="top" title="Hapus" class="fas fa-trash text-danger"></i> </a>
                        </td>
                    </tr>
                    {% endfor %}       
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock contents %}

{% block modals %}
<div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-right">
                <div class="row">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
             </div>
            <div class="modal-body">
                {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
            </div>
        </div>
    </div>
</div>
{% endblock modals %}

{% block scripts %}
{% endblock scripts %}

app/templates/categories/edit.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base_admin.html" %}

{% block styles %}
{% endblock styles %}
    
{% block breadcrumbs %}
<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="/admin"><i class="fas fa-tachometer-alt"></i> Beranda Administrator</a></li>
    <li class="breadcrumb-item"><a href="/admin/kategori"><i class="fas fa-users"></i> Kategori</a></li>
    <li class="breadcrumb-item active">{{title}}</li>
</ol>
{% endblock breadcrumbs %}

{% block contents %}
{{ utils.flashed_messages(dismissible=True) }}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                {{ wtf.quick_form(form, button_map={'submit': 'primary'}) }}
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

{% block modals %}
{% endblock modals %}

{% block scripts %}
{% endblock scripts %}